sudo: required

services:
- docker

language: go

go:
  - 1.8
  - 1.9

env:
  global:
    - BUILD_GOARCH=amd64
  matrix:
    - BUILD_GOOS=linux
    - BUILD_GOOS=darwin

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
